language: cpp

compiler:
  - gcc
  - clang

branches:
  only:
    - master

install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libqt4-dev subversion

script:
  - svn checkout -q http://sparsehash.googlecode.com/svn/trunk sparsehash-read-only
  - cd sparsehash-read-only
  - ./configure
  - make -j2
  - cp -R src/sparsehash ../
  - cp -R src/google ../
  - cd ../tests
  - qmake
  - make -j2
  - for i in ./tst_*; do ./$i; done
