language: cpp

compiler:
  - gcc
  - clang

branches:
  only:
    - master

sudo: false

addons:
  apt:
    packages:
    - libqt4-dev

script:
  - git clone https://github.com/google/sparsehash
  - cd sparsehash
  - ./configure
  - make -j2
  - cp -R src/sparsehash ../
  - cp -R src/google ../
  - cd ../tests
  - qmake
  - make -j2
  - for i in ./tst_*; do ./$i; done
